get:
  summary: List all products
  description: Retrieves a paginated list of all products available for purchase.
  operationId: listProducts
  tags:
    - Products
  parameters:
    - $ref: ../components/parameters/page.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            required:
              - data
              - pagination
            properties:
              data:
                type: array
                items:
                  $ref: ../components/schemas/Product.yaml
              pagination:
                allOf:
                  - $ref: ../components/schemas/Pagination.yaml
                  - properties:
                      nextPageUrl:
                        example: https://api.letsbook.app/v1/products?page=2
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '429':
      $ref: ../components/responses/TooManyAttempts.yaml
    '500':
      $ref: ../components/responses/InternalServerError.yaml
